const data = {
  rspCode: '00000000',
  rspDesc: '成功',
  data: {
    resourceList: [
      {
        id: '1723224204934971395',
        parentId: '0',
        menuName: '表单表格',
        menuUrl: '/custom-card',
        menuIcon: '',
        menuCode: 'customCard',
        redirectUrl: '',
        perms: null,
        permsType: 'Y',
        isRoute: 'Y',
        sort: 1,
      },
      {
        id: '1723224204934971397',
        parentId: '0',
        menuName: '普通表格',
        menuUrl: '/table',
        menuIcon: '',
        menuCode: 'table',
        redirectUrl: '',
        perms: null,
        permsType: 'Y',
        isRoute: 'Y',
        sort: 3,
      },
      {
        id: '1723224204934971396',
        parentId: '0',
        menuName: '表单组件',
        menuUrl: '/form',
        menuIcon: '',
        menuCode: 'form',
        redirectUrl: '',
        perms: null,
        permsType: 'Y',
        isRoute: 'Y',
        sort: 2,
      },
      {
        id: '1723224204934971398',
        parentId: '0',
        menuName: '上传表格',
        menuUrl: '/table-upload',
        menuIcon: '',
        menuCode: 'tableUpload',
        redirectUrl: '',
        perms: null,
        permsType: 'Y',
        isRoute: 'Y',
        sort: 4,
      },
      {
        id: '1723224244934971397',
        parentId: '0',
        menuName: '403',
        menuUrl: '/403',
        menuIcon: '',
        menuCode: '403',
        redirectUrl: '',
        perms: null,
        permsType: 'Y',
        isRoute: 'Y',
        sort: 6,
      },
      {
        id: '1723224264934971398',
        parentId: '0',
        menuName: '404',
        menuUrl: '/404',
        menuIcon: '',
        menuCode: '404',
        redirectUrl: '',
        perms: null,
        permsType: 'Y',
        isRoute: 'Y',
        sort: 5,
      },
      {
        id: '1723224264934971399',
        parentId: '0',
        menuName: 'not-found',
        menuUrl: '/not-found',
        menuIcon: '',
        menuCode: '404',
        redirectUrl: '',
        perms: null,
        permsType: 'Y',
        isRoute: 'Y',
        sort: 7,
      },
    ],
  },
};

export default data;
